<?xml version="1.0"?>
<package format="3">
  <name>arm_solve_real_server2</name>
  <version>0.0.0</version>
  <description>MoveIt plan with hash-table mapping</description>
  <maintainer email="1258654033@qq.com">xwt</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>moveit_ros_planning_interface</depend>
  <depend>sensor_msgs</depend>
  <depend>trajectory_msgs</depend>
  <depend>geometry_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>