<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robot_interfaces</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="X13903105060@gmail.com">xwt</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <!-- .action C++接口 生成依赖 -->
  <buildtool_depend>rosidl_default_generators</buildtool_depend>  

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <!-- 运行时依赖 -->
  <exec_depend>rosidl_default_runtime</exec_depend>

  <depend>geometry_msgs</depend>

  <!-- 
      ROS2 在构建时需要识别：哪些包是：接口包
      因此 包含 .msg/ .action/ 和 .srv/ 必须在 package.xml 中
      声明 “<member_of_group>rosidl_interface_packages</member_of_group>”    
  -->
  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
